- name: Ansible Copy Example Local to Remote
  hosts: all
  tasks:
     - name: Install Apache
       yum: name=httpd update_cache=yes state=latest
      
    - name: copying file with playbook
      become: true 
      copy:
        src: /var/lib/jenkins/workspace/ansible/index.html
        dest: /var/www/html/
